import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/header'
import './globals.css'
// import './utils/utils'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BlockPool',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#0f0f0f] bg-[url('/back_img.svg')] bg-cover bg-no-repeat">
        <Header />
        {children}
      </body>
    </html>
  )
}
